joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.0
    autorepeat_rate: 20.0

teleop_node:
  ros__parameters:
    axis_linear.x: 1
    scale_linear.x: 0.1
    scale_linear_turbo.x: 0.2

    axis_angular.yaw: 0
    scale_angular.yaw: 0.1
    scale_angular_turbo.yaw: 0.2


    enable_turbo_button: 3

    require_enable_button: false